<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="System.Management" Version="10.0.12" />
    <PackageVersion Include="PdfPig" Version="0.1.17-alpha-202609071845-0d1d6" />
  </ItemGroup>
</Project>
