<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PocketAI.Core\PocketAI.Core.csproj" />
    <ProjectReference Include="..\PocketAI.Hardware\PocketAI.Hardware.csproj" />
  </ItemGroup>
</Project>
