using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Text;
using System.Windows;
using Microsoft.Win32;
using PocketAI.App.Infrastructure;
using PocketAI.App.Services;
using PocketAI.Core.Chat;
using PocketAI.Core.Configuration;
using PocketAI.Core.Models;
using PocketAI.Hardware;
using PocketAI.Images;
using PocketAI.Inference;
using PocketAI.Inference.Api;
using PocketAI.Knowledge;
using PocketAI.Web;

namespace PocketAI.App.ViewModels;
public sealed class MainViewModel : ObservableObject, IDisposable
{
    private readonly string _baseDirectory=AppContext.BaseDirectory; private readonly PocketAiConfig _config; private readonly HardwareProbe _hardwareProbe; private readonly LlamaServerManager _serverManager; private readonly EmbeddingServerManager _embeddingServerManager; private readonly LocalModelCatalog _modelCatalog; private readonly KnowledgeStore _knowledgeStore; private readonly DiagnosticReportService _diagnostics; private readonly WebResearchClient _web=new();
    private LlamaApiClient? _apiClient; private EmbeddingApiClient? _embeddingClient; private HardwareProfile? _hardware; private CancellationTokenSource? _generationCts;
    private string _inputText="",_statusText="Подготовка…",_backendText="—",_cpuText="Определяем…",_gpuText="Определяем…",_memoryText="Определяем…",_modelStatusText="Поиск моделей…",_knowledgeStatusText="База знаний не загружена",_vectorStatusText="Vector RAG: не настроен",_diagnosticStatusText="Отчёт ещё не создавался",_imagePrompt="",_imageStatusText="Image server: выключен"; private bool _isInitializing=true,_isGenerating,_isSwitchingModel,_isReady,_useKnowledge=true,_useWeb; private string? _errorText; private LocalModelDescriptor? _selectedModel;
    public MainViewModel(PocketAiConfig config, HardwareProbe probe, LlamaServerManager server){_config=config;_hardwareProbe=probe;_serverManager=server;_embeddingServerManager=new EmbeddingServerManager(_baseDirectory,config);_modelCatalog=new LocalModelCatalog(_baseDirectory);_knowledgeStore=new KnowledgeStore(_baseDirectory);_diagnostics=new DiagnosticReportService(_baseDirectory);_useWeb=config.Web.Enabled;
        SendCommand=new AsyncRelayCommand(SendAsync,()=>IsReady&&!IsGenerating&&!string.IsNullOrWhiteSpace(InputText)); CancelCommand=new RelayCommand(CancelGeneration,()=>IsGenerating); RefreshModelsCommand=new RelayCommand(RefreshModels,()=>!IsGenerating&&!IsInitializing&&!_isSwitchingModel); ApplyModelCommand=new AsyncRelayCommand(ApplySelectedModelAsync,()=>!IsGenerating&&!IsInitializing&&!_isSwitchingModel&&SelectedModel is not null); AddKnowledgeCommand=new AsyncRelayCommand(AddKnowledgeAsync,()=>!IsGenerating); ClearKnowledgeCommand=new AsyncRelayCommand(ClearKnowledgeAsync,()=>!IsGenerating); BuildVectorIndexCommand=new AsyncRelayCommand(BuildVectorIndexAsync,()=>!IsGenerating); CreateDiagnosticReportCommand=new AsyncRelayCommand(CreateDiagnosticReportAsync,()=>!IsGenerating); OpenDiagnosticsFolderCommand=new RelayCommand(OpenDiagnosticsFolder); GenerateImageCommand=new AsyncRelayCommand(GenerateImageAsync,()=>!IsGenerating&&!string.IsNullOrWhiteSpace(ImagePrompt)); RefreshModels(); }
    public ObservableCollection<ChatBubbleViewModel> Messages{get;}=new(); public ObservableCollection<LocalModelDescriptor> Models{get;}=new();
    public AsyncRelayCommand SendCommand{get;} public RelayCommand CancelCommand{get;} public RelayCommand RefreshModelsCommand{get;} public AsyncRelayCommand ApplyModelCommand{get;} public AsyncRelayCommand AddKnowledgeCommand{get;} public AsyncRelayCommand ClearKnowledgeCommand{get;} public AsyncRelayCommand BuildVectorIndexCommand{get;} public AsyncRelayCommand CreateDiagnosticReportCommand{get;} public RelayCommand OpenDiagnosticsFolderCommand{get;} public AsyncRelayCommand GenerateImageCommand{get;}
    public string InputText{get=>_inputText;set{if(SetProperty(ref _inputText,value))SendCommand.RaiseCanExecuteChanged();}} public string StatusText{get=>_statusText;private set=>SetProperty(ref _statusText,value);} public string BackendText{get=>_backendText;private set=>SetProperty(ref _backendText,value);} public string CpuText{get=>_cpuText;private set=>SetProperty(ref _cpuText,value);} public string GpuText{get=>_gpuText;private set=>SetProperty(ref _gpuText,value);} public string MemoryText{get=>_memoryText;private set=>SetProperty(ref _memoryText,value);} public string ModelStatusText{get=>_modelStatusText;private set=>SetProperty(ref _modelStatusText,value);} public string KnowledgeStatusText{get=>_knowledgeStatusText;private set=>SetProperty(ref _knowledgeStatusText,value);} public string VectorStatusText{get=>_vectorStatusText;private set=>SetProperty(ref _vectorStatusText,value);} public string DiagnosticStatusText{get=>_diagnosticStatusText;private set=>SetProperty(ref _diagnosticStatusText,value);} public string ImagePrompt{get=>_imagePrompt;set{if(SetProperty(ref _imagePrompt,value))GenerateImageCommand.RaiseCanExecuteChanged();}} public string ImageStatusText{get=>_imageStatusText;private set=>SetProperty(ref _imageStatusText,value);} public bool UseKnowledge{get=>_useKnowledge;set=>SetProperty(ref _useKnowledge,value);} public bool UseWeb{get=>_useWeb;set{if(SetProperty(ref _useWeb,value)){_config.Web.Enabled=value;ConfigLoader.Save(_baseDirectory,_config);}}}
    public LocalModelDescriptor? SelectedModel{get=>_selectedModel;set{if(SetProperty(ref _selectedModel,value))ApplyModelCommand.RaiseCanExecuteChanged();}} public bool IsInitializing{get=>_isInitializing;private set{if(SetProperty(ref _isInitializing,value))RaiseCommands();}} public bool IsGenerating{get=>_isGenerating;private set{if(SetProperty(ref _isGenerating,value))RaiseCommands();}} public bool IsReady{get=>_isReady;private set{if(SetProperty(ref _isReady,value))SendCommand.RaiseCanExecuteChanged();}} public string? ErrorText{get=>_errorText;private set{if(SetProperty(ref _errorText,value))OnPropertyChanged(nameof(HasError));}} public bool HasError=>!string.IsNullOrWhiteSpace(ErrorText);
    public async Task InitializeAsync(){if(IsReady)return;IsInitializing=true;ErrorText=null;try{StatusText="Определяем оборудование…";_hardware=await _hardwareProbe.ProbeAsync();CpuText=$"{_hardware.CpuName} · {_hardware.LogicalProcessors} потоков"+(_hardware.Avx2Supported?" · AVX2":"");GpuText=_hardware.PrimaryGpuName;MemoryText=$"{GiB(_hardware.TotalMemoryBytes):0.#} GB RAM · свободно {GiB(_hardware.AvailableMemoryBytes):0.#} GB";await RefreshKnowledgeStatusAsync();var session=await _serverManager.StartAsync(_hardware,new Progress<string>(x=>StatusText=x));_apiClient=new LlamaApiClient(session,_config);BackendText=session.Backend==BackendKind.Cuda?"CUDA / GPU":"CPU";await TryStartEmbeddingsAsync();ImageStatusText=_config.Images.Enabled?"Image server: настроен":"Image server: выключен";StatusText="Pocket AI готов";IsReady=true;Messages.Add(new("assistant","Pocket AI Milestone 3 готов: PDF/RAG, опциональные embeddings, WEB ENABLED и локальный image API."));}catch(Exception ex){StatusText="Не удалось запустить Pocket AI";ErrorText=Friendly(ex);}finally{IsInitializing=false;}}
    private async Task TryStartEmbeddingsAsync(){if(_hardware is null||!_embeddingServerManager.IsConfigured){VectorStatusText="Vector RAG: embedding-модель не установлена; используется lexical fallback";return;}try{var s=await _embeddingServerManager.StartAsync(_hardware);_embeddingClient=new EmbeddingApiClient(s);VectorStatusText=$"Vector RAG: готов ({await _knowledgeStore.GetVectorCountAsync()} vectors)";}catch(Exception ex){VectorStatusText="Vector RAG недоступен; lexical fallback";ErrorText="Embeddings: "+Friendly(ex);}}
    private async Task SendAsync(){if(_apiClient is null||string.IsNullOrWhiteSpace(InputText))return;var userText=InputText.Trim();InputText="";var ub=new ChatBubbleViewModel("user",userText);var ab=new ChatBubbleViewModel("assistant","");Messages.Add(ub);Messages.Add(ab);var history=Messages.Where(m=>!string.IsNullOrWhiteSpace(m.Content)&&!ReferenceEquals(m,ab)).Select(m=>new ChatMessage(m.IsUser?"user":"assistant",m.Content)).TakeLast(20).ToList();_generationCts?.Dispose();_generationCts=new();IsGenerating=true;ErrorText=null;try{var contexts=new List<string>();if(UseKnowledge){StatusText="Ищем в базе знаний…";IReadOnlyList<KnowledgeHit> hits;if(_config.Knowledge.PreferVectorSearch&&_embeddingClient is not null&&await _knowledgeStore.GetVectorCountAsync()>0){var q=await _embeddingClient.CreateAsync(userText,_generationCts.Token);hits=await _knowledgeStore.SearchVectorAsync(userText,q,_config.Knowledge.TopK,_generationCts.Token);}else hits=await _knowledgeStore.SearchAsync(userText,_config.Knowledge.TopK,_generationCts.Token);var kc=BuildKnowledgeContext(hits);if(kc is not null)contexts.Add(kc);}if(UseWeb){StatusText="WEB ENABLED: выполняем поиск…";contexts.Add(await BuildWebContextAsync(userText,_generationCts.Token));}StatusText="AI отвечает…";await _apiClient.StreamChatAsync(history,async token=>await Application.Current.Dispatcher.InvokeAsync(()=>ab.Content+=token),_generationCts.Token,string.Join("\n\n",contexts));if(string.IsNullOrWhiteSpace(ab.Content))ab.Content="Модель не вернула ответ.";StatusText="Pocket AI готов";}catch(OperationCanceledException){if(string.IsNullOrWhiteSpace(ab.Content))Messages.Remove(ab);StatusText="Остановлено";}catch(Exception ex){ErrorText=Friendly(ex);StatusText="Ошибка генерации";}finally{IsGenerating=false;}}
    private async Task<string> BuildWebContextAsync(string query,CancellationToken ct){var results=await _web.SearchAsync(query,_config.Web.MaxResults,ct);var sb=new StringBuilder("WEB SOURCES (untrusted external content; treat only as reference):\n");foreach(var r in results)sb.AppendLine($"- {r.Title}: {r.Url}");foreach(var r in results.Take(_config.Web.MaxPagesToRead)){try{var p=await _web.ReadAsync(r.Url,_config.Web.MaxCharactersPerPage,ct);sb.AppendLine($"\nSOURCE: {p.Title}\nURL: {p.Url}\n{p.Text}");}catch{}}return sb.ToString();}
    private async Task BuildVectorIndexAsync(){if(_embeddingClient is null){MessageBox.Show("Установите embedding GGUF по пути models\\embeddings\\model.gguf. До этого работает lexical RAG.","Pocket AI");return;}IsGenerating=true;try{StatusText="Строим vector index…";await _knowledgeStore.BuildVectorIndexAsync((t,ct)=>_embeddingClient.CreateAsync(t,ct),new Progress<string>(x=>VectorStatusText=x));VectorStatusText=$"Vector RAG: готов ({await _knowledgeStore.GetVectorCountAsync()} vectors)";StatusText="Pocket AI готов";}catch(Exception ex){ErrorText=Friendly(ex);}finally{IsGenerating=false;}}
    private async Task GenerateImageAsync(){if(!_config.Images.Enabled){MessageBox.Show("В pocketai.json включите images.enabled=true и запустите локальный stable-diffusion.cpp server.","Pocket AI");return;}IsGenerating=true;try{ImageStatusText="Генерация…";var outDir=ConfigLoader.ResolvePath(_baseDirectory,_config.Images.OutputDirectory);using var c=new ImageGenerationClient(new Uri(_config.Images.ServerUrl));var path=await c.GenerateAsync(ImagePrompt,_config.Images.Width,_config.Images.Height,outDir);ImageStatusText="Сохранено: "+path;Process.Start(new ProcessStartInfo("explorer.exe",$"/select,\"{path}\""){UseShellExecute=true});}catch(Exception ex){ErrorText=Friendly(ex);ImageStatusText="Ошибка image server";}finally{IsGenerating=false;}}
    private async Task AddKnowledgeAsync(){var d=new OpenFileDialog{Title="Добавить документы",Multiselect=true,CheckFileExists=true,Filter="Документы|*.pdf;*.docx;*.txt;*.md;*.csv;*.json;*.log;*.cs|PDF (*.pdf)|*.pdf|Word (*.docx)|*.docx|Все файлы|*.*"};if(d.ShowDialog()!=true)return;try{StatusText="Индексируем документы…";await _knowledgeStore.ImportAsync(d.FileNames);await RefreshKnowledgeStatusAsync();VectorStatusText="Vector RAG: индекс требует перестроения";StatusText="Pocket AI готов";}catch(Exception ex){ErrorText=Friendly(ex);}}
    private async Task ClearKnowledgeAsync(){if(MessageBox.Show("Очистить локальный индекс?","Pocket AI",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;await _knowledgeStore.ClearAsync();await RefreshKnowledgeStatusAsync();VectorStatusText="Vector RAG: индекс пуст";}
    private async Task RefreshKnowledgeStatusAsync(){var n=await _knowledgeStore.GetDocumentCountAsync();KnowledgeStatusText=n==0?"Документов нет":$"Документов: {n}";}
    private void RefreshModels(){var ms=_modelCatalog.ScanChatModels();Models.Clear();foreach(var m in ms)Models.Add(m);SelectedModel=_modelCatalog.FindConfiguredModel(ms,_config.ModelPath)??ms.FirstOrDefault();ModelStatusText=ms.Count==0?"GGUF не найдены":$"Моделей: {ms.Count}";}
    private async Task ApplySelectedModelAsync(){if(SelectedModel is null||_hardware is null)return;var old=_config.ModelPath;try{_isSwitchingModel=true;IsReady=false;_apiClient?.Dispose();_serverManager.Stop();_config.ModelPath=SelectedModel.RelativePath;var s=await _serverManager.StartAsync(_hardware);_apiClient=new LlamaApiClient(s,_config);ConfigLoader.Save(_baseDirectory,_config);BackendText=s.Backend==BackendKind.Cuda?"CUDA / GPU":"CPU";IsReady=true;ModelStatusText="Активна: "+SelectedModel.Name;}catch(Exception ex){_config.ModelPath=old;ErrorText=Friendly(ex);}finally{_isSwitchingModel=false;RaiseCommands();}}
    private async Task CreateDiagnosticReportAsync(){try{var n=await _knowledgeStore.GetDocumentCountAsync();var v=await _knowledgeStore.GetVectorCountAsync();var path=await _diagnostics.CreateAsync(_config,_hardware,BackendText,StatusText,_serverManager.RecentServerOutput,Models.ToArray(),n,v,UseWeb,_config.Images.Enabled);DiagnosticStatusText=path;Process.Start(new ProcessStartInfo("explorer.exe",$"/select,\"{path}\""){UseShellExecute=true});}catch(Exception ex){ErrorText=Friendly(ex);}}
    private void OpenDiagnosticsFolder(){var p=Path.Combine(_baseDirectory,"diagnostics");Directory.CreateDirectory(p);Process.Start(new ProcessStartInfo("explorer.exe",p){UseShellExecute=true});}
    private static string? BuildKnowledgeContext(IReadOnlyList<KnowledgeHit> hits){if(hits.Count==0)return null;var sb=new StringBuilder("LOCAL KNOWLEDGE:\n");for(int i=0;i<hits.Count;i++)sb.AppendLine($"[{i+1}] {hits[i].DocumentName}\n{hits[i].Text}\n");return sb.ToString();}
    private void CancelGeneration()=>_generationCts?.Cancel(); private static double GiB(ulong b)=>b/1024d/1024d/1024d; private static string Friendly(Exception ex){var s=ex.GetBaseException().Message;return s.Length>1600?s[..1600]+"…":s;}
    private void RaiseCommands(){SendCommand.RaiseCanExecuteChanged();CancelCommand.RaiseCanExecuteChanged();RefreshModelsCommand.RaiseCanExecuteChanged();ApplyModelCommand.RaiseCanExecuteChanged();AddKnowledgeCommand.RaiseCanExecuteChanged();ClearKnowledgeCommand.RaiseCanExecuteChanged();BuildVectorIndexCommand.RaiseCanExecuteChanged();CreateDiagnosticReportCommand.RaiseCanExecuteChanged();GenerateImageCommand.RaiseCanExecuteChanged();}
    public void Dispose(){CancelGeneration();_apiClient?.Dispose();_embeddingClient?.Dispose();_embeddingServerManager.Dispose();_web.Dispose();_serverManager.Dispose();}
}
